### ISSUE TITLE
მოკავშირე ფილდები თავში დაუწერე ხოლმე

### ISSUE THREAD

**Issue by MariamKipshidze** [natia02/TbcCRUD#1]
https://github.com/natia02/TbcCRUD/blob/cd67b6ad2a8c333301b466dbf120fef5a0e3b133/EasyStock/models/product.py#L9

**Comment by natia02** [comment]
შენიშვნა მიღებულია მაგრამ მე ბოლოში უფრო მეკომფორტულება ხოლმე, გავასწორებ

**Comment by MariamKipshidze** [comment]
@natia02 მოკავშირე ფილდები მოდელის თავში არის ბევრად უფრო მარტივი მისაგნები და აღსაქმელი, კოდის გარჩევის დროს ეს გეხმარება მარტივად წარმოიდგინო ბაზის სტრუქტურა, მაგრამ თუ შენთვის ასე კომფორტულია შეგიძლია შენი სურვილისამებრ დაწერო
